app-host = "{{app.name}}"
app-port = "80"
prov-app-docker-img = "dolibarr/dolibarr:develop"
prov-app-ha-topology = "flex"

[deployment]

  [[deployment.paths]]
    dockerpath = "/var/www/html/custom"
    level = 0
    name = "path-volume-dolibarr-custom"
    srcname = "dolibarr-custom"
    srcpath = "."
    srctype = "volume"

  [[deployment.paths]]
    dockerpath = "/var/www/documents"
    level = 0
    name = "path-volume-dolibarr-documents"
    srcname = "dolibarr-documents"
    srcpath = "."
    srctype = "volume"

  [[deployment.routes]]
    cname = "{{app.name}}.{{name}}.{{config.cloud18SubDomain}}-{{config.cloud18SubDomainZone}}.{{config.cloud18Domain}}.cloud18.io"
    port = "{{app.port}}"
    primary = true
    protocol = "https"
  [deployment.storages]

    [[deployment.storages.volumes]]
      name = "dolibarr-custom"
      poolname = "tank"
      volumedir = "dolibarr_custom"

    [[deployment.storages.volumes]]
      name = "dolibarr-documents"
      poolname = "tank"
      volumedir = "dolibarr_documents"

  [[deployment.variables]]
    locked = false
    name = "DOLI_INIT_DEMO"
    type = "env"
    value = "0"

  [[deployment.variables]]
    locked = false
    name = "DOLI_DB_HOST"
    type = "env"
    value = "{{proxies.0.name}}"

  [[deployment.variables]]
    locked = false
    name = "DOLI_DB_NAME"
    type = "env"
    value = "dolidb"

  [[deployment.variables]]
    locked = false
    name = "DOLI_DB_USER"
    type = "env"
    value = "dolidbuser"

  [[deployment.variables]]
    locked = false
    name = "DOLI_DB_PASSWORD"
    type = "secret"
    value = "dolidbpass"

  [[deployment.variables]]
    locked = false
    name = "DOLI_URL_ROOT"
    type = "env"
    value = "http://0.0.0.0"

  [[deployment.variables]]
    locked = false
    name = "DOLI_ADMIN_LOGIN"
    type = "env"
    value = "admin"

  [[deployment.variables]]
    locked = false
    name = "DOLI_ADMIN_PASSWORD"
    type = "secret"
    value = "admin"

  [[deployment.variables]]
    locked = false
    name = "DOLI_CRON"
    type = "env"
    value = "0"

  [[deployment.variables]]
    locked = false
    name = "DOLI_CRON_KEY"
    type = "secret"
    value = "mycronsecurekey"

  [[deployment.variables]]
    locked = false
    name = "DOLI_COMPANY_NAME"
    type = "env"
    value = "MyBigCompany"
